# Example Taskfile for testing Jarvis Task (go-task) integration
# See: https://taskfile.dev/
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Default task
    cmds:
      - echo "{{.GREETING}}"

  # @emoji 🔨
  build:
    desc: Build the project
    cmds:
      - cargo build

  # @emoji 🧪
  test:
    desc: Run tests
    deps: [build]
    cmds:
      - cargo test

  # @emoji ✅
  # @description Run clippy linter and format checker
  check:
    desc: Run clippy and format check
    cmds:
      - cargo clippy -- -D warnings
      - cargo fmt -- --check

  # @emoji 🧹
  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  # @ignore
  _internal_helper:
    desc: Internal helper task (hidden from TUI)
    cmds:
      - echo "This is an internal helper"
