name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `jarvis`
        2. Navigate to...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Jarvis Version
      description: Output of `jarvis --version`
      placeholder: "0.1.5"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 14.0 / Ubuntu 22.04 / etc."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Output
      description: Any relevant error messages
      render: shell
